#!/usr/bin/env python3

import os
from argparse import ArgumentParser


def main():
    # Parse arguments
    parser = ArgumentParser()
    parser.add_argument("args", nargs="*")
    args, unknown_args = parser.parse_known_args()
    # pprint(args)
    # pprint(unknown_args)

    all_args = args.args + unknown_args
    # pprint(all_args)

    # Check which TeX Live to use
    texlive_dir = "/app/texlive/bin"
    if os.path.isdir(texlive_dir):
        # print("Using TeX Live Flatpak")
        use_tex_live_from_host = False
    else:
        # print("Using TeX Live from host")
        use_tex_live_from_host = True

    # Build the command string
    command = ""
    for arg in all_args:
        # Add quotes if spaces are present
        if " " in arg:
            arg = f'"{arg}"'
        command += f" {arg}"

    # Add flatpak-spawn if needed
    if use_tex_live_from_host:
        command = f"flatpak-spawn --host {command}"

    # print and execute the command
    # print(f"command: {command}")
    os.system(command)


if __name__ == "__main__":
    main()
